[package]
name = "rust-text-draw"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
cosmic-text = { version = "0.12" }
serde = { version = "1.0.209", features = ["derive"], default-features = false }
json5 = "0.4.1"
